### ISSUE TITLE
`Noned` implementation for `char` is undefined behavior

### ISSUE THREAD

**Issue by tbu-** [llogiq/optional#22]
I think that having a `char` with an invalid value is undefined behavior: https://doc.rust-lang.org/stable/nomicon/meet-safe-and-unsafe.html. It might work today, but compiler optimizations can break it.

A possible way out would be to store it in a `u32` variable instead, which isn't really possible with the current `Noned` trait. Maybe it could be changed to have an associated type that is used for the `Optioned` struct -- then the `bool` special case could also go away.

**Comment by CAD97** [comment]
As the person who implemented partial for `char`, I feel I should answer this.

`char` is always four bytes in size. <https://doc.rust-lang.org/std/primitive.char.html#representation>

`char::from_u32_unsafe` is just a transmute call. <https://doc.rust-lang.org/src/core/char.rs.html#173-175>

_Using_ a `char` which is not a valid, non-surrogate codepoint is unsafe, because all safe fn assume that `char`s are valid, non-surrogate codepoints. _Having_ a `char` which is not a valid, non-surrogate codepoint is unsafe in that it cannot be used as a `char`, but the behavior is defined, because a `char` is defined to be four bytes behind the scenes.

(We could switch the none value of `char` to be `char::MAX as u32 + 1` which would avoid it being undefined whether a `char` comparison is signed or unsigned comparison of the four bytes. _That_ might be worth it, now that I think about it.)

**Comment by llogiq** [comment]
The contract for `char` states that it always contains a valid character, so since our field *contains* one, we are bound by its invariants – or may (or may not) suffer the consequences should the implementation change to rely on that invariant.

So I'm rather thinking about adding an associated type defaulting to `Self`, but overwrite it to be `u32` for `char` (note that this is still problematic because on some systems char could be signed).

**Comment by tbu-** [comment]
> Having a char which is not a valid, non-surrogate codepoint is unsafe in that it cannot be used as a char, but the behavior is defined, because a char is defined to be four bytes behind the scenes.

No, this is not OK. It might work today, but it can always go wrong once LLVM is informed about the `char` type having an integer between 0 and `0x10FFFF`. When Rust tells that to LLVM, the check for `None` can be optimized out, because LLVM knows that a read from a `char` variable (whether directly or indirectly, through a `transmute`) can never yield a `0x110000`.

**Comment by tbu-** [comment]
> (note that this is still problematic because on some systems char could be signed).

The `char` that can be signed or not is the C type `char`, not the Rust one.

**Comment by CAD97** [comment]
Another option is to decide on a valid `char` to remove from the pot if unsafe-hacking in `u32::MAX as char` or `char::MAX as u32 + 1 as char` is considered too unsafe.

In two tiers:

- Use a surrogate value. That's in the range `U+0000` - `U+10FFFF`, but an unsafe Rust `char`.
- Use `'\0'`. That's a valid Rust `char`, but _unlikely_ to show up in UTF-8 text (but not impossible).

**Comment by tbu-** [comment]
https://github.com/rust-lang/rust/pull/45225 contains code that will make unwanted behavior more likely.

**Comment by CAD97** [comment]
For what it's worth, rust-lang/rust#45225 also makes the `Noned` impl for `char` unnecessary as `Option<char>` will be four bytes, the same size as a `char`.

Also FWIW, using `'\0'` as the `None` makes sense (though isn't perfect) as well, as it's not going to show up in anything but the most eccentric of use cases.

**Comment by CAD97** [comment]
Current version on crates.io (`0.3.0`) still has the old unsound behavior. If possible I'd recommend yanking 0.3.0 and publishing a new version with this patch in.

**Comment by llogiq** [comment]
Thank you, I published 0.4.0
