### ISSUE TITLE
Update documentation for compiler improvements.

### ISSUE THREAD

**Issue by rnleach** [llogiq/optional#33]
Compiler optimizations over the years since this crate was made have made the `OptionBool` type [obsolete](https://users.rust-lang.org/t/list-of-fundamental-crates/17806/5?u=ryan). If I took the time to make a pull request to remove or deprecate that part of the crate, would you accept it?

Would you prefer to remove them and bump the version to 0.5 or to deprecate them and bump it to 0.4.2?

**Comment by llogiq** [comment]
The OptionBool may be *almost* obsolete, but there are still use cases where it will outperform Option<bool> due to special handling of e.g. slices and iterators, so I wouldn't want to remove it outright. I'm open to documentation PRs that tell people the space benefit no longer applies and to benchmark their code first before choosing OptionBool.
